name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # This will update every day at midnight
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-wakatime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: WakaTime Action
        uses: WakaTime/actions-cli@v1
        with:
          api_key: ${{ secrets.WAKATIME_API_KEY }}
