name: Waka Readme Stats

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  push:
    branches:
      - main

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
